#!/usr/bin/python

import ephem,sys

date = sys.argv[1] + " 00:00:00"

mercury = ephem.Mercury()
mercury.compute(date)
mercurye = ephem.Ecliptic(mercury)
print("Mercury:", mercurye.lon)

venus = ephem.Venus()
venus.compute(date)
venuse = ephem.Ecliptic(venus)
print("Venus:", venuse.lon)

mars = ephem.Mars()
mars.compute(date)
marse = ephem.Ecliptic(mars)
print("Mars:", marse.lon)


jupiter = ephem.Jupiter()
jupiter.compute(date)
jupitere = ephem.Ecliptic(jupiter)
print("Jupiter:", jupitere.lon)

saturn = ephem.Saturn()
saturn.compute(date)
saturne = ephem.Ecliptic(saturn)
print("Saturn:", saturne.lon)

